import mongoose from "mongoose";

// _id -> autogenerated

const StockAnalysisSchema = new mongoose.Schema(
  {
    date: {
      type: Date,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    directionPlanned: {
      type: String,
      required: true,
    },
    actualMove: {
      type: String,
      required: true,
    },
    analysisResult: {
      type: String,
      enum: ["correct", "incorrect"],
      required: true,
    },
    remarks: {
      type: String,
    },
  },
  { timestamps: true }
);

const StockAnalysis = new mongoose.model("StockAnalysis", StockAnalysisSchema);

export default StockAnalysis;
